parking:
  total-spots: 100

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parking_db
    username: postgres
    password: 1923
    driver-class-name: org.postgresql.Driver
  batch:
      jdbc:
        initialize-schema: always
      job:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 50
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
logging:
  level:
    org.springframework.batch: INFO